// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMessages.Data;

namespace MyMessages.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210401183340_AddStickersTable")]
    partial class AddStickersTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyMessages.Data.Entities.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("MyMessages.Data.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("Date")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<int?>("FileId")
                        .HasColumnType("int");

                    b.Property<int?>("PictureId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique()
                        .HasFilter("[FileId] IS NOT NULL");

                    b.HasIndex("PictureId")
                        .IsUnique()
                        .HasFilter("[PictureId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MyMessages.Data.Entities.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("MyMessages.Data.Entities.Sticker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stickers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apricot",
                            Path = "stickers\\apricot.png"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Calendula",
                            Path = "stickers\\calendula.png"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chamomile",
                            Path = "stickers\\chamomile.png"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cloud",
                            Path = "stickers\\cloud.png"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Flowers",
                            Path = "stickers\\flowers.png"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Heart",
                            Path = "stickers\\heart.png"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Hills",
                            Path = "stickers\\hills.png"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Mallow",
                            Path = "stickers\\mallow.png"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Mushroom",
                            Path = "stickers\\mushroom.png"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Rainbow",
                            Path = "stickers\\rainbow.png"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Sun",
                            Path = "stickers\\sun.png"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Tree",
                            Path = "stickers\\tree.png"
                        });
                });

            modelBuilder.Entity("MyMessages.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin",
                            PasswordHash = "21232f297a57a5a743894a0e4a801fc3"
                        });
                });

            modelBuilder.Entity("MyMessages.Data.Entities.Message", b =>
                {
                    b.HasOne("MyMessages.Data.Entities.File", "File")
                        .WithOne("Message")
                        .HasForeignKey("MyMessages.Data.Entities.Message", "FileId");

                    b.HasOne("MyMessages.Data.Entities.Picture", "Picture")
                        .WithOne("Message")
                        .HasForeignKey("MyMessages.Data.Entities.Message", "PictureId");

                    b.HasOne("MyMessages.Data.Entities.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
